# -*- coding: utf-8 -*-
"""inference_classification_teeth_noteeth.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jc96jtXyJlJaEUJT135ZF1KFuprhc5jR
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
from tensorflow import keras
import numpy as np

# define model path and pass image path
model_filepath = "/content/drive/MyDrive/Colab Notebooks/teeth_classification/models/model_29-06-2021_02:21.h5"
img_path = "/content/drive/MyDrive/Colab Notebooks/teeth_classification/dataset/test/noteeth/COCO_test2014_000000460979.jpg"

# input parameters
img_height = 150
img_width = 150
threshold = 0.5

# load model
model = keras.models.load_model(model_filepath)

# prepare image to feed to model
img = tf.keras.utils.load_img(img_path, target_size=(img_height, img_width))
img_array = tf.keras.utils.img_to_array(img)
img_array = tf.expand_dims(img_array, 0) # Create a batch

# run predictions
predictions = model.predict(img_array)

# calc confidence and find label
confidence = (predictions[0][0])*100
labels = (np.where(predictions > threshold, 1,0))[0][0]

# show output
print(labels)   # 0 = no_teeth, 1 = teeth
print(confidence)   # shows the confidence of detection

